CREATE TABLE `coach_access` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`coachId` int NOT NULL,
	`grantedAt` timestamp NOT NULL DEFAULT (now()),
	`revokedAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	CONSTRAINT `coach_access_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cycleId` int NOT NULL,
	`userId` int NOT NULL,
	`dayNumber` int NOT NULL,
	`entryDate` timestamp NOT NULL DEFAULT (now()),
	`b1q1` int NOT NULL DEFAULT 0,
	`b1q2` int NOT NULL DEFAULT 0,
	`b1q3` int NOT NULL DEFAULT 0,
	`b1q4` int NOT NULL DEFAULT 0,
	`b1q5` int NOT NULL DEFAULT 0,
	`b1q6` int NOT NULL DEFAULT 0,
	`b1q7` int NOT NULL DEFAULT 0,
	`sumB1` int NOT NULL DEFAULT 0,
	`b2q1` int NOT NULL DEFAULT 0,
	`b2q2` int NOT NULL DEFAULT 0,
	`b2q3` int NOT NULL DEFAULT 0,
	`b2q4` int NOT NULL DEFAULT 0,
	`b2q5` int NOT NULL DEFAULT 0,
	`b2q6` int NOT NULL DEFAULT 0,
	`b2q7` int NOT NULL DEFAULT 0,
	`sumB2` int NOT NULL DEFAULT 0,
	`b3q1` int NOT NULL DEFAULT 0,
	`b3q2` int NOT NULL DEFAULT 0,
	`b3q3` int NOT NULL DEFAULT 0,
	`b3q4` int NOT NULL DEFAULT 0,
	`b3q5` int NOT NULL DEFAULT 0,
	`b3q6` int NOT NULL DEFAULT 0,
	`b3q7` int NOT NULL DEFAULT 0,
	`sumB3` int NOT NULL DEFAULT 0,
	`b4q1` int NOT NULL DEFAULT 0,
	`b4q2` int NOT NULL DEFAULT 0,
	`b4q3` int NOT NULL DEFAULT 0,
	`b4q4` int NOT NULL DEFAULT 0,
	`b4q5` int NOT NULL DEFAULT 0,
	`b4q6` int NOT NULL DEFAULT 0,
	`b4q7` int NOT NULL DEFAULT 0,
	`sumB4` int NOT NULL DEFAULT 0,
	`b5q1` int NOT NULL DEFAULT 0,
	`b5q2` int NOT NULL DEFAULT 0,
	`b5q3` int NOT NULL DEFAULT 0,
	`b5q4` int NOT NULL DEFAULT 0,
	`b5q5` int NOT NULL DEFAULT 0,
	`b5q6` int NOT NULL DEFAULT 0,
	`b5q7` int NOT NULL DEFAULT 0,
	`sumB5` int NOT NULL DEFAULT 0,
	`b6q1` int NOT NULL DEFAULT 0,
	`b6q2` int NOT NULL DEFAULT 0,
	`b6q3` int NOT NULL DEFAULT 0,
	`b6q4` int NOT NULL DEFAULT 0,
	`b6q5` int NOT NULL DEFAULT 0,
	`b6q6` int NOT NULL DEFAULT 0,
	`b6q7` int NOT NULL DEFAULT 0,
	`sumB6` int NOT NULL DEFAULT 0,
	`b7q1` int NOT NULL DEFAULT 0,
	`b7q2` int NOT NULL DEFAULT 0,
	`b7q3` int NOT NULL DEFAULT 0,
	`b7q4` int NOT NULL DEFAULT 0,
	`b7q5` int NOT NULL DEFAULT 0,
	`b7q6` int NOT NULL DEFAULT 0,
	`b7q7` int NOT NULL DEFAULT 0,
	`sumB7` int NOT NULL DEFAULT 0,
	`b8q1` int NOT NULL DEFAULT 0,
	`b8q2` int NOT NULL DEFAULT 0,
	`b8q3` int NOT NULL DEFAULT 0,
	`b8q4` int NOT NULL DEFAULT 0,
	`b8q5` int NOT NULL DEFAULT 0,
	`b8q6` int NOT NULL DEFAULT 0,
	`b8q7` int NOT NULL DEFAULT 0,
	`sumB8` int NOT NULL DEFAULT 0,
	`totalDayScore` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `daily_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `test_cycles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`startDate` timestamp NOT NULL DEFAULT (now()),
	`endDate` timestamp,
	`status` enum('active','completed','abandoned') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `test_cycles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','coach') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` ADD `consentGiven` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `users` ADD `consentGivenAt` timestamp;